services:
  mysqlDB:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=MYDB
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql


volumes:
  db-data: