"""rename column description fk_business_category_id fk_owner_id to table business

Revision ID: 247ab1e462ac
Revises: a212b771d2af
Create Date: 2024-08-07 09:44:35.289337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.libs.sql_alchemy_lib import Base
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision: str = '247ab1e462ac'
down_revision: Union[str, None] = 'a212b771d2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('business', sa.Column('fk_business_category_id', sa.Integer(), nullable=True))
    op.add_column('business', sa.Column('fk_owner_id', mysql.CHAR(length=36), nullable=True))
    op.drop_constraint('business_ibfk_1', 'business', type_='foreignkey')
    op.drop_constraint('business_ibfk_2', 'business', type_='foreignkey')
    op.create_foreign_key(None, 'business', 'users', ['fk_owner_id'], ['id'])
    op.create_foreign_key(None, 'business', 'business_category', ['fk_business_category_id'], ['id'])
    op.drop_column('business', 'describe')
    op.drop_column('business', 'owner_id')
    op.drop_column('business', 'business_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('business_category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('business', sa.Column('owner_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('business', sa.Column('describe', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.create_foreign_key('business_ibfk_2', 'business', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('business_ibfk_1', 'business', 'business_category', ['business_category_id'], ['id'])
    op.drop_column('business', 'fk_owner_id')
    op.drop_column('business', 'fk_business_category_id')
    op.drop_column('business', 'description')
    # ### end Alembic commands ###
