"""changed type data column id to BusinessCategory table

Revision ID: 3a53e43af6b7
Revises: 47d6a34dd1b3
Create Date: 2024-08-07 08:23:04.396080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.libs.sql_alchemy_lib import Base
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision: str = '3a53e43af6b7'
down_revision: Union[str, None] = '47d6a34dd1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_category', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_business_category_id', table_name='business_category')
    op.create_index(op.f('ix_business_category_id'), 'business_category', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_category_id'), table_name='business_category')
    op.create_index('ix_business_category_id', 'business_category', ['id'], unique=True)
    op.alter_column('business_category', 'id',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
