"""add business_category table

Revision ID: 47d6a34dd1b3
Revises: da2867bc8f2e
Create Date: 2024-08-07 06:24:08.402716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.libs.sql_alchemy_lib import Base
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision: str = '47d6a34dd1b3'
down_revision: Union[str, None] = 'da2867bc8f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_category',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_category_id'), 'business_category', ['id'], unique=True)
    op.create_index(op.f('ix_business_category_name'), 'business_category', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_category_name'), table_name='business_category')
    op.drop_index(op.f('ix_business_category_id'), table_name='business_category')
    op.drop_table('business_category')
    # ### end Alembic commands ###
