"""add user_needs_model table

Revision ID: 5e9ccfb5d66d
Revises: 247ab1e462ac
Create Date: 2024-08-07 09:59:07.399533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.libs.sql_alchemy_lib import Base
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision: str = '5e9ccfb5d66d'
down_revision: Union[str, None] = '247ab1e462ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_needs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('fk_business_category_id', sa.Integer(), nullable=True),
    sa.Column('fk_user_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['fk_business_category_id'], ['business_category.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_needs_id'), 'user_needs', ['id'], unique=False)
    op.create_index(op.f('ix_user_needs_title'), 'user_needs', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_needs_title'), table_name='user_needs')
    op.drop_index(op.f('ix_user_needs_id'), table_name='user_needs')
    op.drop_table('user_needs')
    # ### end Alembic commands ###
