"""add rating_model table

Revision ID: a212b771d2af
Revises: cd6fd6f27238
Create Date: 2024-08-07 09:40:11.571993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.libs.sql_alchemy_lib import Base
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision: str = 'a212b771d2af'
down_revision: Union[str, None] = 'cd6fd6f27238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('review_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fk_business_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('fk_rater_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['fk_business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['fk_rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=True)
    op.create_index(op.f('ix_rating_rating_count'), 'rating', ['rating_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_rating_count'), table_name='rating')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
