"""Add health check  table

Revision ID: da2867bc8f2e
Revises: 1befd50cccff
Create Date: 2024-08-06 09:24:41.834957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.libs.sql_alchemy_lib import Base
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision: str = 'da2867bc8f2e'
down_revision: Union[str, None] = '1befd50cccff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcheck',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcheck_id'), 'healthcheck', ['id'], unique=True)
    op.create_index(op.f('ix_healthcheck_name'), 'healthcheck', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthcheck_name'), table_name='healthcheck')
    op.drop_index(op.f('ix_healthcheck_id'), table_name='healthcheck')
    op.drop_table('healthcheck')
    # ### end Alembic commands ###
